#!/usr/bin/python3
import sys
from math import sqrt, floor


def findFactors(num):
    for i in range(2, 100):
        if num % i == 0:
            return num // i, i
    n = floor(sqrt(num))
    if n % 2 == 0:
        n += 1
    while n < num:
        if num % n == 0:
            return (n, num // n)
        n += 2


if len(sys.argv) != 2:
    print(f"Usage: {sys.argv[0]} <file>", file=sys.stderr)
    exit(1)

filename = sys.argv[1]
with open(filename, "r") as file:
    line = file.readline()
    while line:
        num = int(line)
        factors = findFactors(num)
        if factors is not None:
            p, q = factors
            print(f"{num}={p}*{q}")
        line = file.readline()
